### PR TITLE
Added rowkey support NLog Renders

### PR DESCRIPTION
**Pull request by zirain**

### CODE REVIEW

**Comment by snakefoot** [comment]
Maybe try to make a combined solution:

https://github.com/JDetmar/NLog.Extensions.AzureStorage#table-configuration

Have you tried [NLog.Extensions.AzureCosmosTable](https://www.nuget.org/packages/NLog.Extensions.AzureCosmosTable/) that also works for Azure Table Storage?

**Comment by zirain** [comment]
> Maybe try to make a combined solution:
> 
> https://github.com/JDetmar/NLog.Extensions.AzureStorage#table-configuration
> 
> Have you tried [NLog.Extensions.AzureCosmosTable](https://www.nuget.org/packages/NLog.Extensions.AzureCosmosTable/) that also works for Azure Table Storage?

https://github.com/JDetmar/NLog.Extensions.AzureStorage/blob/fcaab2554aaebbf51e84ce3aac017c9a40b564c2/src/NLog.Extensions.AzureCosmosTable/TableStorageTarget.cs#L207

looks like also do not support

**Comment by snakefoot** [comment]
> looks like also do not support

Yes you are right. Can fix this easily with NLog 4.7, since the current logic is currently hard to override. Lets see who get there first :)

**Comment by snakefoot** [comment]
@zirain Damn it you won the race. But anyway here is my PR for the same feature:

https://github.com/JDetmar/NLog.Extensions.AzureStorage/pull/65

And here is the nuget-package::

https://www.nuget.org/packages/NLog.Extensions.AzureCosmosTable/

Btw. it gives bad performance to re-parse the NLog-Layout for every logevent. Better to change the RowKey-property to have the type `Layout` upfront in `AzureTableStorageTarget`

**Pull request merged**
